### ISSUE TITLE
Unable to create another system item

### ISSUE THREAD

**Issue by lmenale** [benvonh/.snowflake#1]
Hi
I'm having some problems installing your configuration on my laptop.

I've substituted every instance of your "zeph" and "ben" but this didn't work.
Could you please support me?

**Comment by benvonh** [comment]
Haha I didn't plan this to be used by others but sure.

Can you be more descriptive on what the problem is? You haven't said what the problem was. For starters, have you copied your laptop's hardware configuration? Assuming you know how NixOS and Nix Flakes work, after you install NixOS you should run `nixos-generate-config --show-hardware-config > /path/to/flake/systems/zeph/hardware.nix`. Then, you can rebuild switch with the flake and it should just work. Make sure to edit all the files under `systems/` to be what you want.
